### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by ritz078** [stewdio/beep.js#1]
These features will make this plugin very usable :smile: 
- on bower and npm
- minified version
- Task automation (Grunt or Gulp)
- demo file inside demo folder

**Comment by stewdio** [comment]
Hi Ritz. Thanks for the suggestions. I’m going to table those items for now (Bower, NPM, minification, and task automation) as I have some other things in mind that need priority. I’ll return to these issues when the time is right. Currently I feel that keeping the number of files small, being able to run Beep right off the desktop with no server, and not adding anything that requires command-line knowledge is the way to go. As for additional demos beyond the one it loads up with? That’s in the pipeline :)
