### ISSUE TITLE
Beep is not a beep, but a tone

### ISSUE THREAD

**Issue by designbyadrian** [stewdio/beep.js#6]
As it keeps playing as you hold the key.

Should be ToneJS.

:wink:

**Comment by stewdio** [comment]
Hi Adrian, nice to meet you. I see what you mean about beep vs. tone. There’s already an incredible library named [Tone.js](https://github.com/tambien) created by @tambien, et al. so I couldn’t very well steal the name of it :wink: (I do think Tone.js and Beep.js focus on slightly different areas and can actually play very nicely together.)

I suppose I was influenced by the cuteness of the [Road Runner](http://en.wikipedia.org/wiki/Wile_E._Coyote_and_The_Road_Runner)’s “Meep. Meep” and [Herbie](http://en.wikipedia.org/wiki/Herbie,_the_Love_Bug)’s horn honk. But this [Johnny Greenwood](http://en.wikipedia.org/wiki/Jonny_Greenwood) GIF is what I consciously had in mind:

![Beep.js](http://i.imgur.com/od0AkWu.gif)

So I needed a name that was short, preferably cute, and I was hoping for an available URL. “Tone” was out. No Meep, Meep. No Bleepity Bloop. But “Beep” felt about right, even if not strictly correct. And there you have it.

**Comment by voznesenskym** [comment]
@stewdio  best Github comment ever? I say yes.

**Comment by lehni** [comment]
http://bleepjs.com/ : )
